### ISSUE TITLE
你好，请问，您有试过用proto6.8吗？ 希望有时间分享一下。

### ISSUE THREAD

**Issue by Gixiv** [TerryBeanX2/protobufjs-Demo#1]
protobuf.js  最新版本，好像不支持写js了，如果支持，还是期待，前辈写一下，分享一下.

**Comment by TerryBeanX2** [comment]
@LuXiZhong 6版本没用过，当时就图个方便用的5，帮别人弄得，自己这没这个需求，所以我这应该暂时不会写~
